"""
Theme CSS utilities.
"""

from .theme_colors_utils import COLORS


def get_main_stylesheet() -> str:
    """Return the base application stylesheet for the professional theme."""
    lines = [
        "/* Main Application Styles */",
        "QDialog {",
        f"    background-color: {COLORS['light']};",
        "    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\",",
        "        Roboto, \"Helvetica Neue\", Arial, sans-serif;",
        "}",
        "",
        "/* Group Box Styling */",
        "QGroupBox {",
        "    font-weight: bold;",
        f"    border: 2px solid {COLORS['border']};",
        "    border-radius: 8px;",
        "    margin-top: 1ex;",
        "    background-color: white;",
        "    padding-top: 10px;",
        "}",
        "",
        "QGroupBox::title {",
        "    subcontrol-origin: margin;",
        "    left: 10px;",
        "    padding: 0 10px;",
        f"    color: {COLORS['dark']};",
        "    font-size: 14px;",
        "    font-weight: 600;",
        "}",
        "",
        "/* Label Styling */",
        "QLabel {",
        f"    color: {COLORS['dark']};",
        "    font-size: 13px;",
        "    font-weight: 500;",
        "}",
        "",
        "/* Input Field Styling */",
        "QLineEdit, QDateEdit, QComboBox {",
        f"    border: 1px solid {COLORS['border']};",
        "    border-radius: 4px;",
        "    padding: 8px 12px;",
        "    background-color: white;",
        "    font-size: 13px;",
        "    min-height: 20px;",
        "}",
        "",
        "QLineEdit:focus, QDateEdit:focus, QComboBox:focus {",
        f"    border-color: {COLORS['primary']};",
        "    background-color: #f8f9ff;",
        "    outline: none;",
        "}",
        "",
        "QComboBox::drop-down {",
        "    border: none;",
        "    width: 20px;",
        "}",
        "",
        "QComboBox::down-arrow {",
        "    image: url(down_arrow.png);",
        "    width: 12px;",
        "    height: 12px;",
        "}",
        "",
        "/* Button Styling */",
        "QPushButton {",
        "    border-radius: 6px;",
        "    padding: 10px 16px;",
        "    font-size: 13px;",
        "    font-weight: 500;",
        "    border: none;",
        "    min-width: 80px;",
        "    min-height: 20px;",
        "}",
        "",
        "QPushButton:enabled {",
        f"    background-color: {COLORS['primary']};",
        "    color: white;",
        "}",
        "",
        "QPushButton:enabled:hover {",
        f"    background-color: {COLORS['hover']};",
        "}",
        "",
        "QPushButton:pressed {",
        f"    background-color: {COLORS['primary']};",
        "}",
        "",
        "QPushButton:disabled {",
        f"    background-color: {COLORS['secondary']};",
        "    color: #adb5bd;",
        "}",
        "",
        "/* Table Styling */",
        "QTableWidget {",
        f"    gridline-color: {COLORS['border']};",
        f"    selection-background-color: {COLORS['primary']};",
        "    selection-color: white;",
        f"    border: 1px solid {COLORS['border']};",
        "    border-radius: 4px;",
        "    background-color: white;",
        "}",
        "",
        "QHeaderView::section {",
        "    background-color: #f8f9fa;",
        "    padding: 8px;",
        f"    border: 1px solid {COLORS['border']};",
        "    font-weight: 600;",
        f"    color: {COLORS['dark']};",
        "    font-size: 12px;",
        "}",
        "",
        "QTableWidget::item {",
        "    padding: 8px;",
        "    border-bottom: 1px solid #f1f3f4;",
        "}",
        "",
        "QTableWidget::item:selected {",
        f"    background-color: {COLORS['primary']};",
        "    color: white;",
        "}",
        "",
        "/* Progress Bar Styling */",
        "QProgressBar {",
        f"    border: 2px solid {COLORS['border']};",
        "    border-radius: 4px;",
        "    text-align: center;",
        f"    background-color: {COLORS['light']};",
        "    min-height: 25px;",
        "}",
        "",
        "QProgressBar::chunk {",
        f"    background-color: {COLORS['primary']};",
        "    border-radius: 2px;",
        "}",
        "",
        "/* Scroll Bar Styling */",
        "QScrollBar:vertical {",
        f"    background-color: {COLORS['light']};",
        "    border: none;",
        "    width: 14px;",
        "    margin: 0;",
        "}",
        "",
        "QScrollBar::handle:vertical {",
        f"    background-color: {COLORS['muted']};",
        "    border-radius: 7px;",
        "    min-height: 30px;",
        "}",
        "",
        "QScrollBar::handle:vertical:hover {",
        f"    background-color: {COLORS['secondary']};",
        "}",
        "",
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {",
        "    border: none;",
        "    background: none;",
        "}",
        "",
        "/* Status Message Styling */",
        ".status-info {",
        "    background-color: #d1ecf1;",
        "    border: 1px solid #bee5eb;",
        "    border-radius: 4px;",
        "    padding: 10px;",
        "    color: #0c5460;",
        "    font-size: 13px;",
        "    font-weight: 500;",
        "}",
        "",
        ".status-success {",
        "    background-color: #d4edda;",
        "    border: 1px solid #c3e6cb;",
        "    border-radius: 4px;",
        "    padding: 10px;",
        "    color: #155724;",
        "    font-size: 13px;",
        "    font-weight: 500;",
        "}",
        "",
        ".status-warning {",
        "    background-color: #fff3cd;",
        "    border: 1px solid #ffeaa7;",
        "    border-radius: 4px;",
        "    padding: 10px;",
        "    color: #856404;",
        "    font-size: 13px;",
        "    font-weight: 500;",
        "}",
        "",
        ".status-error {",
        "    background-color: #f8d7da;",
        "    border: 1px solid #f5c6cb;",
        "    border-radius: 4px;",
        "    padding: 10px;",
        "    color: #721c24;",
        "    font-size: 13px;",
        "    font-weight: 500;",
        "}",
    ]
    return "\n".join(lines)


def _groupbox_style(border_color: str, title_color: str) -> str:
    lines = [
        "QGroupBox {",
        "    font-weight: bold;",
        f"    border: 2px solid {border_color};",
        "    border-radius: 8px;",
        "    margin-top: 1ex;",
        "    background-color: white;",
        "}",
        "",
        "QGroupBox::title {",
        "    subcontrol-origin: margin;",
        "    left: 10px;",
        "    padding: 0 10px;",
        f"    color: {title_color};",
        "    font-size: 14px;",
        "}",
    ]
    return "\n".join(lines)


_GROUPBOX_STYLES = {
    "default": _groupbox_style(COLORS["border"], COLORS["dark"]),
    "blue": _groupbox_style(COLORS["primary"], COLORS["primary"]),
    "green": _groupbox_style(COLORS["success"], COLORS["success"]),
    "purple": _groupbox_style("#6f42c1", "#6f42c1"),
    "red": _groupbox_style(COLORS["danger"], COLORS["danger"]),
}


def get_groupbox_style(theme: str = "default") -> str:
    """Return CSS for a themed group box."""
    return _GROUPBOX_STYLES.get(theme, _GROUPBOX_STYLES["default"])
